import type { Metadata } from "next";
import localFont from "next/font/local";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { GoogleAnalytics } from '@next/third-parties/google'

const manrope = Manrope({ subsets: ["latin"] });

const GOOGLE_ANALYTICS_ID = process.env.NEXT_PUBLIC_GA_ID;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const neueMontreal = localFont({
  src: "./fonts/NeueMontreal.woff",
  variable: "--font-neue-montreal",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Monet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${neueMontreal.variable} ${manrope.className} bg-black   antialiased`}
      >
        <Navbar />
        {children}
      </body>
      <GoogleAnalytics gaId={GOOGLE_ANALYTICS_ID!} />
    </html>
  );
}
